### ISSUE TITLE
Support for sampling in Vertx

### ISSUE THREAD

**Issue by nitishgoyal13** [eclipse-vertx/vertx-tracing#15]
#### Describe the feature

Ability to sample requests passing through vert.x application

**Comment by nitishgoyal13** [comment]
@vietj Is it possible for you to kindly provide an update on this? It's a blocker for us to start using zipkin with vert.x

**Comment by vietj** [comment]
can you elaborate on this feature and give more information ?

**Comment by vietj** [comment]
I set to 4.0.1 as fix date to ensure it does not get forgotten

**Comment by nitishgoyal13** [comment]
I meant that Sampling option inside `ZipkinTracingOptions` is hard coded to `Sampler.ALWAYS_SAMPLE`
I feel, we should provide the application an ability to supply Sampler from outside so that all sampling options supported by Brave can be used in ZipkinTracingOptions

**Comment by vietj** [comment]
Sure we can do that, do you mind doing a contribution for this ?

**Comment by tsegismont** [comment]
Closed in 03d5753
