### ISSUE TITLE
Span timings aren't collected in case of any 5xx error 

### ISSUE THREAD

**Issue by nitishgoyal13** [eclipse-vertx/vertx-tracing#25]
### Questions

Span timings aren't getting collected in case of any 5xx error.

### Version

4.0.0

<img width="1136" alt="oie_gr4991DAnK6Q" src="https://user-images.githubusercontent.com/12368831/113567103-960b1180-962b-11eb-81be-140d88f987f7.png">

Happening consistently with all the spans with error

**Comment by vietj** [comment]
do you have a reproducer ? it is possible that some span are ignored by the tracing tool if you are using sampling

**Comment by nitishgoyal13** [comment]
Could a span without duration could be creating an issue?
{
  "traceId": "e101cf9a6eaa3755",
  "parentId": "e101cf9a6eaa3755",
  "id": "f610c17b720d6343",
  "kind": "SERVER",
  "name": "publish",
  "localEndpoint": {
    "serviceName": "xxx",
    "ipv4": "a.b.c.d"
  },
  "shared": true
}

In case of 5xx, I am always seeing one span with name = "publish" and this is always without duration. Could this be creating issue?

**Comment by nitishgoyal13** [comment]
This span with empty duration is getting created in `ZipkinTracer` class and `receiveRequest` method with operation as publish

**Comment by nitishgoyal13** [comment]
For now, I have done this as a workaround

```
if (policy == TracingPolicy.IGNORE || operation.equalsIgnoreCase("publish")) {
      return null;
    }
```

**Comment by vietj** [comment]
do you have a reproducer ?
