### ISSUE TITLE
Span decorators for open tracing

### ISSUE THREAD

**Issue by langera** [eclipse-vertx/vertx-tracing#27]
#### Describe the feature

Add the ability to decorate spans (e.g. set custom tags, modify operation name) by defining the behaviour once (decorator class) and using it in multiple services / contexts.

#### Use cases

We want to have the ability as the infra (SRE) layer of a company to provide service developers with a simple integration to add custom tags in our traces. 

An easy way to do it is to simply use the Decorator design pattern and define such decorators for the span.
We want to write a decorator once and give an easy way for the service owner to plug it in to their own tracing options when launching their vertx service.

see: [https://github.com/langera/vertx-tracing/blob/open-tracing-decorator/vertx-opentracing/src/main/java/io/vertx/tracing/opentracing/OpenTracingSpanDecorator.java](https://github.com/langera/vertx-tracing/blob/open-tracing-decorator/vertx-opentracing/src/main/java/io/vertx/tracing/opentracing/OpenTracingSpanDecorator.java)

This will allow us to customize the span.

Some of the customization is generic to all traces regardless of scenario or input (typically system property specific to our company). For example:

```
void decorate(Span span, Object ignored) {
	span.setTag("MySepcificAppId", System.getProperty("my.specific.app.id"));
}
```
For other tags, we may have a different way to extract the value in different scenarios, but we still want to share it among services. 

For example, in http requests :
```
 void decorate(Span span, HttpServletRequest request) {
	span.setTag("MySepcificUserId", MyWebAuthUtil.extractUserId(request.getHeader("Authorization")));
}
```
and in a message bus receive scenario: 
```
void decorate(Span span, Message<?, ?> message) {
	span.setTag("MySepcificUserId", MyMsgAuthUtil.extractUserId(message.headers.get("Authorization")));
}
```
We can easily implement a type-specific decorators for each type of object (e.g. HttpServletRequest, Message...)

see: [https://github.com/langera/vertx-tracing/blob/open-tracing-decorator/vertx-opentracing/src/main/java/io/vertx/tracing/opentracing/TypedOpenTracingSpanDecorator.java](https://github.com/langera/vertx-tracing/blob/open-tracing-decorator/vertx-opentracing/src/main/java/io/vertx/tracing/opentracing/TypedOpenTracingSpanDecorator.java)

#### Contribution

Reference implementation (in a fork of v. 4.0.3):

[https://github.com/langera/vertx-tracing/tree/open-tracing-decorator](https://github.com/langera/vertx-tracing/tree/open-tracing-decorator)

**Comment by tsegismont** [comment]
Opentracing is deprecated https://github.com/opentracing/specification/issues/163
