### ISSUE TITLE
I want to print traceid spanid etc in the log but centralized vertx-zipkin has some questions

### ISSUE THREAD

**Issue by zhaoqiang1024** [eclipse-vertx/vertx-tracing#36]
### Questions

I want to print traceid spanid etc in the log but centralized vertx-zipkin has some questions

### Version

4.2.1

### Context

In my project concentrated vertx-zipkin but in the log cannot enter traceId、spanId etc and when looking at the MDC context found that no corresponding variables are assigned to it.What do I do with this problem? or to offer a demo project?

### Do you have a reproducer?

https://github.com/zhaoqiang1024/vertx.demo

### Extra

* macOS

**Comment by sanyarnd** [comment]
Use `OpenTracingUtil.getSpan` and put it in MDC yourself.
