### ISSUE TITLE
Open telemetry. Set span attributes before starting it

### ISSUE THREAD

**Issue by BodySplash** [eclipse-vertx/vertx-tracing#37]
https://github.com/eclipse-vertx/vertx-tracing/blob/84c67438255b1dff58892a2be3bbe52e95d8fdf3/vertx-opentelemetry/src/main/java/io/vertx/tracing/opentelemetry/OpenTelemetryTracer.java#L75

By setting span attributes after starting it, if open telemetry is configured to use a sampler, like [this one](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/samplers/src/main/java/io/opentelemetry/contrib/samplers/RuleBasedRoutingSampler.java), than the sampler cannot take any decision based on the attributes, since it's called on span start. 

Happy to make a PR for that, I just wanted to make sure I wasn't missing any context.

**Comment by vietj** [comment]
thanks, PR is welcome
