### ISSUE TITLE
The `OpenTracingOptions` doesn't set a corresponding factory on creation

### ISSUE THREAD

**Issue by ppatierno** [eclipse-vertx/vertx-tracing#44]
Currently the `OpenTelemetryTracingFactory` class provides a corresponding internal `INSTANCE` which is used when you create `OpenTelemetryOptions` for setting the factory automatically here:

https://github.com/eclipse-vertx/vertx-tracing/blob/master/vertx-opentelemetry/src/main/java/io/vertx/tracing/opentelemetry/OpenTelemetryOptions.java#L33

The same doesn't happen in the `OpenTracingTracerFactory` class where there is no internal `INSTANCE` and the `OpenTracingOptions` doesn't set any factory automatically on creation.

https://github.com/eclipse-vertx/vertx-tracing/blob/master/vertx-opentracing/src/main/java/io/vertx/tracing/opentracing/OpenTracingOptions.java#L19

It means that if both OpenTelemetry and OpenTracing are in the classpath when I am using just an `OpenTracingOptions` instance, I see the application trying to use OpenTelemetry as well because the factory is set while it should use the factory for OpenTracing only.
The workaround I have is to set the factory programmatically when I create the `OpenTracingOptions` (but it's not needed when using OpenTelemetry). Is there any reason for this difference between the two?

**Comment by vietj** [comment]
implementations have been done by different people.

when you have two tracing integration libraries on the classpath, you should force the one you want to use on the tracing options to force it.

However if you are using a dedicated tracing option subclass then it should pick up the correct library as you would like to.

I think that all tracing options subclass should do that.

**Comment by vietj** [comment]
you can provide a PR to fix that for OpenTracing and Zipkin and call it a day

**Comment by ppatierno** [comment]
> when you have two tracing integration libraries on the classpath, you should force the one you want to use on the tracing options to force it.

I agree and you are forcing by creating the right tracing options instance.

> However if you are using a dedicated tracing option subclass then it should pick up the correct library as you would like to.

Yeah, but it's not happening because of what I described.

> you can provide a PR to fix that for OpenTracing and Zipkin and call it a day

Ok, I will try to find the time for this!

**Comment by vietj** [comment]
> 
> Yeah, but it's not happening because of what I described.
> 

the _should_ implied the current behaviour is not correct
