### ISSUE TITLE
Unnecessary transitive dependencies

### ISSUE THREAD

**Issue by mohamnag** [eclipse-vertx/vertx-tracing#49]
### Version

4.3.4

### Context

We got a version conflict on some of the transitive dependencies which is being included due to `com.squareup.okhttp3:okhttp`. I believe this transitive dependency could actually be filtered out here as this can even mess up with threading on Vert.x right?

<img width="462" alt="image" src="https://user-images.githubusercontent.com/4481421/201601578-199c3fdc-1c44-4f97-859d-b6eaff87d1ea.png">

### Do you have a reproducer?

use `mvn dependency:list` on this repo

**Comment by mohamnag** [comment]
by "independent" you mean running on its own threads/thread poll right? what I meant with "interference" was more of a resource interference (by having own threads)

**Comment by tsegismont** [comment]
> by "independent" you mean running on its own threads/thread poll right?

Right

>what I meant with "interference" was more of a resource interference (by having own threads)

I understand, but unless someone contributes a jaeger reporter which uses the Vert.x HTTP client, it's something we'll have to live with. My assumption is the impact should be limited (unless you're uploading tons of trace data).
