### ISSUE TITLE
Span Context is missing in InBoundInterceptor of EventBus

### ISSUE THREAD

**Issue by VishnuTeja27** [eclipse-vertx/vertx-tracing#61]
### Version

4.3.7

### Context

I was trying to calculate the network latency between 2 services communicating via eventbus using inBoundInterceptors and OutboundInterceptors of EventBus. In this process, I saw that the Span context is missing in the InBoundInterceptor in the reciever Verticle.

Upon checking more, i saw that the InBoundInterceptor is being executed even before the spanContext is set from OpenTelemetryTracer.
If this is intended, please let me know why this is the case.

### Steps to reproduce
This can be reproduced/observed from the **EventBusTest** testCase present in the **vertx-opentelemetry** repo. 

1. Add inBoundInterceptor for the ReplyVerticle and print the spanContext with Span.current().getSpanContext()
2. It will be unset (0000...)
3. This can also be easily checked by placing the debugger points at the **InBoundInterceptor** and the **receiveRequest** method in the **OpenTelemetryTracer** Class and sending a request via EventBus.

**Comment by tsegismont** [comment]
I believe this is expected because the span is created just before delivering the message to the consumer (that is, after inbound interceptors have been executed).

If you only need to match span id, you might get it from message headers, I think.

Thoughts @vietj ?

**Comment by vietj** [comment]
that's correct @tsegismont I don't know if that's something we could improve
