### ISSUE TITLE
OpenTelemetry Semantic Convention Miss For Database Spans

### ISSUE THREAD

**Issue by Olamshin** [eclipse-vertx/vertx-tracing#64]
### Version

4.4.6

### Context

It appears that a required attribute for database spans is missing. According to the document [here](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.18.0/specification/trace/semantic_conventions/database.md#connection-level-attributes), `db.system` should be present and is required on database spans. I did not see a reference to it in the codebase and running instances of my application didn't surface the span attribute.

The consequence is that some telemetry backends like New Relic, do not assign the proper designation of the span as a database span.

**Comment by tsegismont** [comment]
Thank you for reporting this @Olamshin !

**Comment by tsegismont** [comment]
Fixed by https://github.com/eclipse-vertx/vertx-sql-client/commit/98bc0299612cb4577dfc9657f60abd1c68435865

**Comment by Olamshin** [comment]
@tsegismont Thanks for the speedy response!
