### ISSUE TITLE
Tracing: more eventbus and HTTP tags

### ISSUE THREAD

**Issue by Olamshin** [eclipse-vertx/vertx-tracing#67]
### Version

4.4.6

### Context

According to the document [here](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.18.0/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions), the following span attribute should be present for HTTP server spans.
- http.scheme
- http.target
- net.host.name
- net.host.port

Absence of these attributes would mean OTel spans from vert.x may not be categorized as HTTP spans by a telemetry backend.

**Comment by tsegismont** [comment]
Thanks for the report, @Olamshin

Would you like to contribute the fix?

**Comment by Olamshin** [comment]
@tsegismont Yes, i can attempt this. Looks like the core changes would [here](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpUtils.java#L69)? Any other tips would be appreciated!

**Comment by tsegismont** [comment]
> @tsegismont Yes, i can attempt this. Looks like the core changes would [here](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpUtils.java#L69)? Any other tips would be appreciated!

Yes, I would start here. Then we need to make sure we don't break other tracing implementations

**Comment by vietj** [comment]
we should keep the actual names and translate them in vertx open tracing when it get the tags. if there are missing tags then we should add them using the same convention

**Comment by tsegismont** [comment]
Resolved by https://github.com/eclipse-vertx/vert.x/pull/5024
