### ISSUE TITLE
Use names specified by OpenTelemetry for tags

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-tracing#69]
In Vert.x 4, tag names should follow the OpenTracing specification (by convention).

OpenTracing is now deprecated: https://github.com/opentracing/specification/issues/163

In Vert.x 5,  tag names should follow the OpenTelemetry specification

This might require to remove/add some adapter code in vertx-tracing (see https://github.com/eclipse-vertx/vertx-tracing/pull/70)

Possibly impacted modules

- [x] Vert.x core https://github.com/eclipse-vertx/vert.x/pull/5331
- [x] SQL Clients https://github.com/eclipse-vertx/vertx-sql-client/pull/1468
- [x] Redis Client https://github.com/vert-x3/vertx-redis-client/pull/476
- [x] Cassandra Client https://github.com/vert-x3/vertx-cassandra-client/pull/86
- [x] Kafka Client https://github.com/vert-x3/vertx-kafka-client/pull/276
- [x] Vert.x Tracing https://github.com/eclipse-vertx/vertx-tracing/pull/81

**Comment by tsegismont** [comment]
@vietj how about deprecating OpenTracing in Vert.x 4 and removing in Vert.x 5 ?

**Comment by vietj** [comment]
I think we should keep it at least for vertx 5 without publishing docs
