### ISSUE TITLE
OTEL - Span.current()/ Baggage.current() is empty after grpc/http2 call

### ISSUE THREAD

**Issue by jianchaoxudd** [eclipse-vertx/vertx-tracing#77]
### Questions
Hi team,
We are trying to retrieve Span or Baggage by using `Span.current()` and `Baggage.current()`. We call a dependency service using vertx-grpc which is a http2 client in our vertx-web service. However, the Span/Baggage is empty after the http2 client call. We debug this by logger like following.

```
1. logger.info("$Span.current()") # does show the proper Span
2. dependency service call
3. logger.info("$Span.current()") # the Span is gone/no longer the same
```

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version
Which version(s) did you encounter this bug ?
4.5.8

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. Span.current()
4. grpc/http client call
5. Span.current() // no longer the same

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by tsegismont** [comment]
Can you provide a small reproducer?

**Comment by tsegismont** [comment]
Thanks for letting us know. I would recommend to report the issue to the corresponding repo.
